### ISSUE TITLE
Support opening of zipped files

### ISSUE THREAD

**Issue by lippmaje** [ref-xx/basinc#11]
v 1.792
It's not possible to open a zipped .TAP file (ex foo.tap.zip), likewise for zipped .BAS files, snapshots etc.
Would be nice to have it.

**Comment by ref-xx** [comment]
I don't think it's necessary. basinc is not an emulator, it's a development environment. So using zipped files is kind of beats the purpose, adding complexity.  I'll leave this open incase someone is interested.

**Comment by ref-xx** [comment]
So no other interest, closing the issue.
