### ISSUE TITLE
font size too small when working in high resolution

### ISSUE THREAD

**Issue by lippmaje** [ref-xx/basinc#14]
v1.794

The font size in some of the windows does not scale with the screen resolution, so on e.g. 1920x1080 it gets barely readable. Screenshot attached.
There should be an option to set the UI font size for Variables, CPU window etc.

![screen](https://github.com/ref-xx/basinc/assets/87007255/ef196947-4e12-486b-a54e-357cfc509f23)

**Comment by ref-xx** [comment]
It's too much work as originally Paul align every button and box manually, but, as a workaround a simple font size selection option is added to the Options. It will only usable with some resizable windows though. I am also suffering from this, I will try to update basinC to be fully 4K monitor compatible by version 2.0
