### ISSUE TITLE
change labels of shadow registers in CPU window

### ISSUE THREAD

**Issue by lippmaje** [ref-xx/basinc#15]
v1.794

The shadow registers in the CPU window are labeled identically to the 'front' registers. If the labels would be more distinctive that would be great. Something like `AF'` `BC'` or so.

![screen](https://github.com/ref-xx/basinc/assets/87007255/26ffaa64-e4ac-4456-af43-0cf002309d54)

**Comment by ref-xx** [comment]
they shown properly with later OS gui's. also those windows are not supported.
![image](https://github.com/ref-xx/basinc/assets/129548/f2b09794-ddcc-48f8-882b-59c84725cc9e)

**Comment by lippmaje** [comment]
I think it's an issue with my font scale, I'm using 150% fonts and the apostrophe ' just was clipped out by the value label next to the register. Thank you for looking into this.
