### ISSUE TITLE
no refresh in the Memory Viewer

### ISSUE THREAD

**Issue by lippmaje** [ref-xx/basinc#16]
If the Memory Viewer is open during debugging and the code changes data, the Viewer still shows the old data. There is no possibility to refresh the view except than closing and reopening the Viewer. A refresh button would be helpful.

![screen](https://github.com/ref-xx/basinc/assets/87007255/890a5e5b-8085-4b6a-892e-7640bfb7309f)

**Comment by ref-xx** [comment]
added to to-do list.

**Comment by ref-xx** [comment]
added in v1.795 (next version)
