### ISSUE TITLE
Line numbers get concatenated when editing a line

### ISSUE THREAD

**Issue by lippmaje** [ref-xx/basinc#17]
v1.794 - but this occurred in all revisions so far, I'm just reporting it now

Sometimes, after editing a line and pressing ENTER, the edited line gets 'combined' with the existing one, resulting in an invalid line number. See screenshot below, after editing line 8210 it becomes line 82108210.
![screen](https://github.com/ref-xx/basinc/assets/87007255/588efa16-1eba-4003-b2bd-511664c26253)

When saving the program, the defective line is **not** saved, so if you close and reopen the program the changed line is lost entirely.

It is possible to undo the glitch by pressing CTRL-z which I am using as workaround, but a fix for this would be welcome.

**Comment by lippmaje** [comment]
It seems to happen randomly, I didn't notice a specific pattern when it occurred.

**Comment by ref-xx** [comment]
there are similar line corruption bugs, probably related to one single cause. Thanks for reporting.

**Comment by ref-xx** [comment]
This is fixed now. (v1.795)
