### ISSUE TITLE
CPU Window disables STOP button

### ISSUE THREAD

**Issue by lippmaje** [ref-xx/basinc#18]
v1.794

Sometimes the STOP button is greyed out without any reason, see the screenshot which was taken during a running program. It should be possible to stop execution when the user monitors the CPU while it executes. The button is enabled most of the time, but sometimes gets disabled and stays so, until the program hits a breakpoint.
I suggest to never disable it, because there seems to be no reason at all why to do this. Just my opinion.

![screen](https://github.com/ref-xx/basinc/assets/87007255/b00f02e0-f708-40d2-a35d-1aa99c4d9fda)

**Comment by ref-xx** [comment]
yes those windows and functions (cpu, assembler etc.) are incomplete and I never worked on them. Note that, CPU emulation is not really accurate, you cannot use basin to create time or flag critical code, the cpu core is there only to execute sinclairbasic commands.

When you see some weird behaviour, (say, cpu window pops up suddenly or locks up) we can safely say that cpu core has crashed. 

I was thinking of removing those functions altogether but I still keep them around until I make sure nobody uses them.

**Comment by ref-xx** [comment]
I'm closing this because assembly related functions are not supported in any way. please use a proper emulator to trace execution.
