### ISSUE TITLE
Profile result window shows 1-byte tokens in strings/comments wrong

### ISSUE THREAD

**Issue by lippmaje** [ref-xx/basinc#5]
`10 LET t$="\#245 <-PRINT": REM \#235 <- FOR`

1-byte tokens located in strings/comments show up wrong in the profiler result window, see screenshot.
![issue_profiler](https://user-images.githubusercontent.com/87007255/184801393-0fea4cb7-3e58-443d-adee-40ef573d2c4f.jpg)

**Comment by ref-xx** [comment]
ok, this is fixed now and will be included in the next release. Latest version is uploaded.
