### ISSUE TITLE
File improvements in Character Editor?

### ISSUE THREAD

**Issue by damieng** [ref-xx/basinc#6]
Hi, any chance we could get a plain "Save" option in the character editor?

I know we have Save As but I'm often refining graphics and have to remember the file name and hope I don't overwrite the wrong one.

Also having Ctrl-S and Ctrl-O for Save and Open as accelerators would also be great. I'd contribute this myself but getting Delphi 5 up and running with the dependencies seems to be a bit of a non-starter.

Also adding *.ch8 as an extension for "Spectrum Font Files" would be great - it's what Recoil has been using so I've also adopted.

**Comment by ref-xx** [comment]
Sure, I'll add it to to-do list.

**Comment by ref-xx** [comment]
this is done, and will be available in 1.794

**Comment by damieng** [comment]
Much appreciated! I must have spent so many hundreds of hours in the BASIN character editor creating all my fonts!
