### ISSUE TITLE
Screen recorder?

### ISSUE THREAD

**Issue by lippmaje** [ref-xx/basinc#8]
This could be an interesting feature. 
Add an option to the Display window to record a series of screens that could be saved as animated GIF or MP4.

**Comment by ref-xx** [comment]
I don't know about this, BasinC's z80 core is not cycle exact (the output window is just a preview, not a real output) and can also occasionally skip frames. it's simply not worth using basinc as a capture target. Export As Tap, or even define your emulator in options>files>external and use CTRL+E on basin to send your basic program to external emulator. 

For creating gif or mp4's, use Spectaculator or ZX Spin, or even use Win+G to capture any compatible target.
